/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.examensegundoparcial;


import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Axel Rosales
 */

public class Principal extends javax.swing.JFrame {
    private List<Double> minutos = new ArrayList<>();
    /**
     * Creates new form Principal
     */
    
    
    public Principal() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddMinutos = new javax.swing.JButton();
        txtMinutosPartido = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResult = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddMinutos.setText("Agregar Minutos");
        btnAddMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMinutosActionPerformed(evt);
            }
        });

        txtMinutosPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinutosPartidoActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtAreaResult.setColumns(20);
        txtAreaResult.setRows(5);
        jScrollPane1.setViewportView(txtAreaResult);

        jLabel1.setText("Minutos");

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Agregue los minutos por cada partido, al finalizar seleccione el boton calcular.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMinutosPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCalcular)
                                .addComponent(btnAddMinutos))
                            .addGap(173, 173, 173))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMinutos)
                    .addComponent(txtMinutosPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMinutosPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinutosPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinutosPartidoActionPerformed

    private void btnAddMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMinutosActionPerformed
                
        if(txtMinutosPartido.getText().isEmpty() || txtMinutosPartido.getText().isBlank()) 
        {
            JOptionPane.showMessageDialog(null,"campo de minutos no valido");
            return;
        }
        
        try
        {
            String minuto =  txtMinutosPartido.getText();            
            double num = Double.parseDouble(minuto);
            
            minutos.add(num);
            
            txtMinutosPartido.setText(null);
            
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null,"El campo de minutos debe ser solo numerico");
            txtMinutosPartido.setText(null);
        }
        
    }//GEN-LAST:event_btnAddMinutosActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        Estadisticas est = new Estadisticas();
        StringBuilder sb = new StringBuilder();
        
        int conteo = 1;
        for(double min: minutos)
        {
            sb.append("Partido " + conteo).append(" " + min + " \n");
            conteo++;
        }
        
        Double promedio = est.PromedioPartidos(minutos);
        sb.append(promedio).append(" Promedio partidos \n");
        
        Double varianza = est.CalcularVarianza(minutos);
        sb.append(varianza).append(" Varianza Partidos \n");
        
        Double desviacion = est.CalcularDesviacionEstandar(minutos);
        sb.append(desviacion).append(" Desviación estandar \n");
        
        Double mediana = est.calcularMediana(minutos);
        sb.append(mediana).append(" Mediana Partido \n");
        
        List<Double> Moda = est.calcularModa(minutos);
        String valModa = "";
        for(double m : Moda)
        {
            valModa += String.valueOf(m);
        }
        valModa = valModa.isEmpty()? "Solo hay valores unicos": valModa;
        sb.append( valModa).append(" Moda Partido\n");
        
        Double rango = est.CalcularRango(minutos);
        sb.append(rango).append(" rango\n");
        
        
        List<Double> OutlinerList = est.EncontrarOutliner(minutos);
        String Outliner = "";
        for(double outl : OutlinerList)
        {
            Outliner = String.valueOf(outl);
        }
        sb.append(Outliner).append(" Outliner(Valores Atipicos) \n");
        
        
        
        
        
        
        
        
        
        txtAreaResult.setText(sb.toString());
        
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMinutos;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JTextArea txtAreaResult;
    private javax.swing.JTextField txtMinutosPartido;
    // End of variables declaration//GEN-END:variables
}
